import pytest
from pathlib import Path
from unittest.mock import MagicMock
from app.services.orchestrator import Orchestrator
from app.adapters import docker_adapter


def _docker_available() -> bool:
    try:
        import docker
        docker.from_env().ping()
        return True
    except Exception:
        return False


@pytest.mark.skipif(not _docker_available(), reason="Docker daemon not available")
def test_deploy_docker_with_autogen():
    orchestrator = Orchestrator()

    # Mock models
    project = MagicMock()
    project.id = 999
    project.workspace_path = r"c:\Users\psing\Desktop\DevOps Agent\apps\demo-app"
    project.has_env_file = True
    project.detected_stack = "node"

    plan = MagicMock()
    plan.image_tag = "test-demo-app:latest"
    plan.dockerfile_path = None
    plan.ports_json = '["8081:8080"]'

    execution = MagicMock()
    execution.id = 111

    session = MagicMock()

    # Mock env storage and DB functions
    import app.services.orchestrator as orch

    # Create dummy env file for test
    dummy_env = Path(project.workspace_path) / ".env.test"
    dummy_env.write_text("APP_PORT=8080\n")

    orch.get_env_for_docker = MagicMock(return_value=str(dummy_env))
    orch.create_deployment = MagicMock()
    orch.update_project = MagicMock()
    orch.get_latest_deployment = MagicMock(return_value=None)
    orch.ensure_execution_allowed = MagicMock()
    orch.append_execution_log = MagicMock()
    orch.settings = MagicMock()
    orch.settings.workspace_root = Path(r"c:\Users\psing\Desktop\DevOps Agent")
    orch.settings.allowed_repo_roots = ""
    orch.settings.dry_run = False

    # Ensure Dockerfile is not there at start
    df = Path(project.workspace_path) / "Dockerfile"
    if df.exists():
        df.unlink()

    # Run the orchestrator deployment
    orchestrator._deploy_docker(project, plan, execution, session, "test-corr-id-2")

    # Assertions
    assert df.exists(), "Dockerfile should have been generated by Orchestrator"

    # Verify container was built and ran
    from app.adapters.docker_adapter import image_exists
    assert image_exists("test-demo-app:latest"), "Image should have been built"

    # Now we shut it down gracefully so it doesn't leak
    client = docker_adapter._get_client()
    containers = client.containers.list(filters={"name": "devops-999-test-corr-id-2"})
    assert len(containers) > 0, "Container should be running"

    containers[0].stop(timeout=1)
    containers[0].remove(force=True)

    df.unlink(missing_ok=True)
    dummy_env.unlink(missing_ok=True)

    print("M3 test successfully built and ran the container!")

if __name__ == "__main__":
    test_deploy_docker_with_autogen()
