"""Detect tech stack and auto-generate a smart Dockerfile if one is missing.

The generator inspects the actual project files (package.json main/scripts,
requirements.txt, pyproject.toml) so the generated Dockerfile is correct for
that specific project — not a one-size-fits-all template.
"""
from __future__ import annotations

import json
from pathlib import Path

from app.common.logging import logger

_log = logger.bind(component="project-analysis")


# ── Stack detection ────────────────────────────────────────────────────────────

def detect_stack(workspace_path: Path) -> str:
    if (workspace_path / "package.json").exists():
        return "node"
    if (workspace_path / "requirements.txt").exists() or (workspace_path / "pyproject.toml").exists():
        return "python"
    if (workspace_path / "Dockerfile").exists() or (workspace_path / "dockerfile").exists():
        return "docker"
    return "unknown"


def get_existing_dockerfile(workspace_path: Path) -> Path | None:
    for name in ("Dockerfile", "dockerfile"):
        p = workspace_path / name
        if p.exists():
            return p
    return None


# ── Smart Node.js Dockerfile generator ────────────────────────────────────────

def _node_dockerfile(workspace_path: Path) -> tuple[str, int]:
    """
    Inspect package.json and return (dockerfile_content, port).

    Logic:
    - Port: read PORT from .env if present, else 8080
    - Start command: use scripts.start if defined, else `node <main>`
    - Install: --production unless a build script exists (then full install + build)
    """
    pkg_path = workspace_path / "package.json"
    try:
        pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
    except Exception:
        pkg = {}

    scripts: dict = pkg.get("scripts", {})
    main_file: str = pkg.get("main", "index.js")

    # Determine port
    port = 8080
    env_file = workspace_path / ".env"
    if env_file.exists():
        for line in env_file.read_text(errors="ignore").splitlines():
            if line.startswith("PORT=") or line.startswith("APP_PORT="):
                val = line.split("=", 1)[1].strip().strip("\"'")
                if val.isdigit():
                    port = int(val)
                break

    # Determine start command
    if "start" in scripts:
        # Use npm start (respects whatever the project defines)
        cmd = '["npm", "start"]'
    else:
        # Fallback: run the main file directly
        cmd = f'["node", "{main_file}"]'

    # Determine whether we need a build step
    has_build = "build" in scripts

    if has_build:
        content = f"""# Auto-generated Dockerfile — Node.js (with build step)
# Generated by AI DevOps Commander based on package.json analysis
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
EXPOSE {port}
CMD {cmd}
"""
    else:
        content = f"""# Auto-generated Dockerfile — Node.js
# Generated by AI DevOps Commander based on package.json analysis
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
EXPOSE {port}
CMD {cmd}
"""
    return content, port


# ── Smart Python Dockerfile generator ─────────────────────────────────────────

def _python_dockerfile(workspace_path: Path) -> tuple[str, int]:
    """
    Inspect requirements.txt / pyproject.toml and Python source files to
    determine the correct framework, entry point, port, and system deps.
    """
    port = 8000
    framework = "unknown"
    system_deps: list[str] = []

    # Read requirements to detect framework and system dependencies
    req_file = workspace_path / "requirements.txt"
    req_text = ""
    if req_file.exists():
        req_text = req_file.read_text(errors="ignore").lower()

    if "fastapi" in req_text or "uvicorn" in req_text:
        framework = "uvicorn"
    elif "flask" in req_text:
        framework = "flask"
    elif "aiohttp" in req_text:
        framework = "aiohttp"
    elif "django" in req_text:
        framework = "django"

    # Detect if OpenCV or image processing libs need system packages
    if "opencv" in req_text or "scikit-image" in req_text:
        system_deps.extend(["libgl1", "libglib2.0-0", "libsm6", "libxext6", "libxrender1"])

    # Detect entry point file
    entry_file = None
    for candidate in ("main.py", "app.py", "server.py", "api.py", "run.py", "manage.py"):
        if (workspace_path / candidate).exists():
            entry_file = candidate
            break

    # Try to detect the actual port from the entry point source
    if entry_file:
        try:
            src = (workspace_path / entry_file).read_text(errors="ignore")
            import re
            # Match patterns like PORT = 8765, port=5000, .run_app(...port=3000)
            for pattern in (
                r'^\s*PORT\s*=\s*(\d+)',
                r'port\s*=\s*(\d+)',
            ):
                m = re.search(pattern, src, re.MULTILINE | re.IGNORECASE)
                if m:
                    port = int(m.group(1))
                    break
        except Exception:
            pass

    # Also check .env for PORT overrides
    env_file = workspace_path / ".env"
    if env_file.exists():
        for line in env_file.read_text(errors="ignore").splitlines():
            if line.startswith("PORT=") or line.startswith("APP_PORT="):
                val = line.split("=", 1)[1].strip().strip("\"'")
                if val.isdigit():
                    port = int(val)
                break

    # Build CMD based on detected framework
    module = entry_file.replace(".py", "") if entry_file else "main"
    if framework == "uvicorn":
        cmd = f'["python", "-m", "uvicorn", "{module}:app", "--host", "0.0.0.0", "--port", "{port}"]'
    elif framework == "flask":
        cmd = f'["python", "-m", "flask", "run", "--host", "0.0.0.0", "--port", "{port}"]'
    elif framework == "django":
        cmd = f'["python", "manage.py", "runserver", "0.0.0.0:{port}"]'
    else:
        # aiohttp, raw scripts, or unknown — run the entry file directly
        cmd = f'["python", "{entry_file or "main.py"}"]'

    has_req = req_file.exists()
    install_cmd = (
        "pip install --no-cache-dir -r requirements.txt"
        if has_req
        else "pip install -e ."
    )

    # Build system deps RUN line if needed
    sys_deps_line = ""
    if system_deps:
        deps_str = " ".join(sorted(set(system_deps)))
        sys_deps_line = f"RUN apt-get update && apt-get install -y --no-install-recommends {deps_str} && rm -rf /var/lib/apt/lists/*\n"

    content = f"""# Auto-generated Dockerfile — Python
# Generated by AI DevOps Commander based on project analysis
FROM python:3.11-slim
WORKDIR /app
{sys_deps_line}{"COPY requirements.txt ./" if has_req else "COPY pyproject.toml ./"}
RUN {install_cmd}
COPY . .
EXPOSE {port}
CMD {cmd}
"""
    return content, port


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_dockerfile(workspace_path: Path, stack: str) -> tuple[Path, int]:
    """Generate and write a smart Dockerfile. Returns (path, port)."""
    if stack == "node":
        content, port = _node_dockerfile(workspace_path)
    elif stack == "python":
        content, port = _python_dockerfile(workspace_path)
    else:
        raise ValueError(
            f"Cannot auto-generate Dockerfile for stack '{stack}'. "
            "Add a Dockerfile manually or ensure your project has package.json (Node) "
            "or requirements.txt / pyproject.toml (Python)."
        )
    path = workspace_path / "Dockerfile"
    path.write_text(content, encoding="utf-8")
    _log.info("dockerfile_generated", path=str(path), stack=stack, port=port)
    return path, port


def analyze_project(workspace_path: Path) -> dict:
    """
    Analyze project. Returns:
    {
        detected_stack: str,
        dockerfile_path: str | None,
        dockerfile_generated: bool,
        default_port: int,
    }
    If no Dockerfile exists, one is auto-generated and dockerfile_generated=True.
    """
    workspace_path = Path(workspace_path)
    if not workspace_path.exists():
        raise FileNotFoundError(f"Workspace does not exist: {workspace_path}")

    stack = detect_stack(workspace_path)
    existing = get_existing_dockerfile(workspace_path)
    generated = False
    default_port = 8080 if stack == "node" else 8000

    if existing:
        dockerfile_path = str(existing)
        # Read port from existing EXPOSE line
        try:
            for line in existing.read_text(errors="ignore").splitlines():
                if line.strip().upper().startswith("EXPOSE "):
                    val = line.strip().split()[1].split("/")[0]
                    if val.isdigit():
                        default_port = int(val)
                    break
        except Exception:
            pass
    else:
        if stack in ("node", "python"):
            path, default_port = generate_dockerfile(workspace_path, stack)
            dockerfile_path = str(path)
            generated = True
        else:
            dockerfile_path = None

    return {
        "detected_stack": stack,
        "dockerfile_path": dockerfile_path,
        "dockerfile_generated": generated,
        "default_port": default_port,
    }
